# Utiliser l'image officielle de python (https://hub.docker.com/_/python)

FROM python:3.9.20-bullseye

# On crée un repertoire app dans notre conteneur pour que ce soit plus lisible
WORKDIR /app

# Copie le fichier requirements.txt avant de lancer pip install
COPY requirements.txt /app

# Installer les dépendances du projet
RUN pip install -r requirements.txt

# Copier le tout dans le workdir
COPY . /app

# port par défaut de flask
EXPOSE 5000

# Commande pour démarrer l'application Flask
CMD ["sh", "-c", "flask db upgrade && flask run --host=0.0.0.0 --port=5000"]
